version: '3'
services:
  backend:
    build:
      context: ./b-end
      dockerfile: Dockerfile
    depends_on:
      - dbpostgres

  frontend:
    build:
      context: ./f-end
      dockerfile: Dockerfile
    depends_on:
      - backend

  nginx:
    image: nginx
    container_name: webserver-node
    restart: always
    ports:
      - ${HOST_SERVER_PORT}:${CONT_SERVER_PORT}
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  dbpostgres:
    image: postgres
    container_name: postgresdb-node
    restart: always
    volumes:
      - pgdb:/var/lib/postgresql/data
      - ./scripts/db.sh:/docker-entrypoint-initdb.d/db.sh

  redis-db:
    image: redis
    container_name: redisdb-node
  
  

volumes:
  pgdb: